export enum HexaNames {
  地 = "地",
  剥 = "剥",
  比 = "比",
  观 = "观",
  豫 = "豫",
  晋 = "晋",
  萃 = "萃",
  否 = "否",
  谦 = "谦",
  山 = "山",
  蹇 = "蹇",
  渐 = "渐",
  小过 = "小过",
  旅 = "旅",
  咸 = "咸",
  遁 = "遁",
  师 = "师",
  蒙 = "蒙",
  水 = "水",
  涣 = "涣",
  解 = "解",
  未济 = "未济",
  困 = "困",
  讼 = "讼",
  升 = "升",
  蛊 = "蛊",
  井 = "井",
  风 = "风",
  恒 = "恒",
  鼎 = "鼎",
  大过 = "大过",
  姤 = "姤",
  复 = "复",
  颐 = "颐",
  屯 = "屯",
  益 = "益",
  雷 = "雷",
  噬嗑 = "噬嗑",
  随 = "随",
  无妄 = "无妄",
  明夷 = "明夷",
  贲 = "贲",
  既济 = "既济",
  家人 = "家人",
  丰 = "丰",
  火 = "火",
  革 = "革",
  同人 = "同人",
  临 = "临",
  损 = "损",
  节 = "节",
  中孚 = "中孚",
  归妹 = "归妹",
  睽 = "睽",
  泽 = "泽",
  履 = "履",
  泰 = "泰",
  大畜 = "大畜",
  需 = "需",
  小畜 = "小畜",
  大壮 = "大壮",
  大有 = "大有",
  夬 = "夬",
  天 = "天",
}

export interface HexaInfo {
  name: HexaNames;
}

export const hexagramMap = [
  { name: HexaNames.地 },
  { name: HexaNames.剥 },
  { name: HexaNames.比 },
  { name: HexaNames.观 },
  { name: HexaNames.豫 },
  { name: HexaNames.晋 },
  { name: HexaNames.萃 },
  { name: HexaNames.否 },
  { name: HexaNames.谦 },
  { name: HexaNames.山 },
  { name: HexaNames.蹇 },
  { name: HexaNames.渐 },
  { name: HexaNames.小过 },
  { name: HexaNames.旅 },
  { name: HexaNames.咸 },
  { name: HexaNames.遁 },
  { name: HexaNames.师 },
  { name: HexaNames.蒙 },
  { name: HexaNames.水 },
  { name: HexaNames.涣 },
  { name: HexaNames.解 },
  { name: HexaNames.未济 },
  { name: HexaNames.困 },
  { name: HexaNames.讼 },
  { name: HexaNames.升 },
  { name: HexaNames.蛊 },
  { name: HexaNames.井 },
  { name: HexaNames.风 },
  { name: HexaNames.恒 },
  { name: HexaNames.鼎 },
  { name: HexaNames.大过 },
  { name: HexaNames.姤 },
  { name: HexaNames.复 },
  { name: HexaNames.颐 },
  { name: HexaNames.屯 },
  { name: HexaNames.益 },
  { name: HexaNames.雷 },
  { name: HexaNames.噬嗑 },
  { name: HexaNames.随 },
  { name: HexaNames.无妄 },
  { name: HexaNames.明夷 },
  { name: HexaNames.贲 },
  { name: HexaNames.既济 },
  { name: HexaNames.家人 },
  { name: HexaNames.丰 },
  { name: HexaNames.火 },
  { name: HexaNames.革 },
  { name: HexaNames.同人 },
  { name: HexaNames.临 },
  { name: HexaNames.损 },
  { name: HexaNames.节 },
  { name: HexaNames.中孚 },
  { name: HexaNames.归妹 },
  { name: HexaNames.睽 },
  { name: HexaNames.泽 },
  { name: HexaNames.履 },
  { name: HexaNames.泰 },
  { name: HexaNames.大畜 },
  { name: HexaNames.需 },
  { name: HexaNames.小畜 },
  { name: HexaNames.大壮 },
  { name: HexaNames.大有 },
  { name: HexaNames.夬 },
  { name: HexaNames.天 },
];
